apiVersion: v1
kind: Service
metadata:
  name: {{ include "static-ip-operator.fullname" . }}
  labels:
    {{- include "static-ip-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 8081
      targetPort: health
      protocol: TCP
      name: health
  selector:
    {{- include "static-ip-operator.selectorLabels" . | nindent 4 }}
