package consts

var (
	DEVELOPMENT             = "DEVELOPMENT"
	LOG_LEVEL               = "LOG_LEVEL"
	LOG_JSON                = "LOG_JSON"
	LOG_ADD_CALLER          = "LOG_ADD_CALLER"
	LOG_DISABLE_STACKTRACE  = "LOG_DISABLE_STACKTRACE"
	LOG_UNESCAPED_MULTILINE = "LOG_UNESCAPED_MULTILINE"
	LOG_COLORIZE_LINE       = "LOG_COLORIZE_LINE"
)
